#!/bin/sh
set -e

echo "weaviate-init: Starting Weaviate configuration process..."

# Check required env vars
if [ -z "$PGHOST" ] || [ -z "$PGUSER" ] || [ -z "$PGPASSWORD" ] || [ -z "$PGDATABASE" ]; then
  echo "weaviate-init: Error: One or more required environment variables are not set."
  echo "PGHOST=$PGHOST, PGUSER=$PGUSER, PGPASSWORD=[set], PGDATABASE=$PGDATABASE"
  exit 1
fi

echo "weaviate-init: Installing required tools..."
apk add --no-cache postgresql-client

echo "weaviate-init: Waiting for database to be ready..."
sleep 5 # Initial wait
# Bounded readiness loop (mirrors n8n install-nodes.sh + minio init-minio.sh
# patterns). A persistently unreachable Supabase DB would otherwise hang the
# init container forever and block the rest of the weaviate-config.env chain.
db_wait=0
db_wait_max=300
until PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$PGPORT" -d "$PGDATABASE" -U "$PGUSER" -c '\q' 2>/dev/null; do
  echo "weaviate-init: Waiting for database..."
  sleep 5
  db_wait=$((db_wait + 5))
  if [ $db_wait -ge $db_wait_max ]; then
    echo "weaviate-init: ERROR — database not reachable after ${db_wait_max}s; aborting." >&2
    exit 1
  fi
done
echo "weaviate-init: Database is available."

echo "weaviate-init: Querying active Ollama embedding models from database..."
# `set -e` at the top of the script would otherwise abort here on any
# psql failure (transient DB issue, public.llms not yet created on a
# fresh init) — bypassing the explicit fallback at the if-then below.
# Append `|| psql_output=""` so the fallback branch actually runs.
psql_output=$(PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$PGPORT" -d "$PGDATABASE" -U "$PGUSER" -t -c "SELECT name FROM public.llms WHERE provider = 'ollama' AND active = true AND embeddings > 0 ORDER BY embeddings DESC LIMIT 1;") || psql_output=""

# Trim whitespace and check result
embedding_model=$(echo "$psql_output" | xargs)

if [ -z "$embedding_model" ]; then
  echo "weaviate-init: No active Ollama embedding models found in database."
  echo "weaviate-init: Falling back to default model: nomic-embed-text"
  embedding_model="nomic-embed-text"
else
  echo "weaviate-init: Found active Ollama embedding model: $embedding_model"
fi

# Create configuration file for Weaviate.
# The embedding model identifier is LiteLLM-prefixed so downstream code can
# pass it straight into LiteLLM's /v1/embeddings request body.
echo "weaviate-init: Creating Weaviate configuration..."
cat > /shared/weaviate-config.env << EOF
# Generated by weaviate-init on $(date)
LITELLM_EMBEDDING_MODEL=ollama/$embedding_model
EOF

echo "weaviate-init: Configuration created:"
cat /shared/weaviate-config.env

# Verify model will be available in Ollama
echo "weaviate-init: Verifying model '$embedding_model' will be pulled by ollama-pull service..."
# Same set -e neutralization as the earlier psql call — the warning
# at the "$model_count" != "1" branch can't fire if psql aborts
# the script before $model_in_db is populated.
model_in_db=$(PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$PGPORT" -d "$PGDATABASE" -U "$PGUSER" -t -c "SELECT count(*) FROM public.llms WHERE provider = 'ollama' AND active = true AND name = '$embedding_model';") || model_in_db=""
model_count=$(echo "$model_in_db" | xargs)

if [ "$model_count" = "1" ]; then
  echo "weaviate-init: ✅ Model '$embedding_model' is configured in database and will be pulled by ollama-pull"
else
  echo "weaviate-init: ⚠️  Warning: Model '$embedding_model' may not be available in Ollama"
fi

echo "weaviate-init: Weaviate configuration process completed successfully."