#!/bin/sh
set -e

echo "weaviate-init: Starting Weaviate configuration process..."

quote_shell_env_value() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# Resolve the embedding model from the environment variable.
# LITELLM_EMBEDDING_MODEL is set in .env (default: ollama/nomic-embed-text)
# and passed into this container by weaviate/compose.yml.
# The value is ALREADY fully-qualified (e.g. "ollama/nomic-embed-text") —
# write it through unchanged.  Do NOT re-prepend "ollama/" here.
model="${LITELLM_EMBEDDING_MODEL:-ollama/nomic-embed-text}"
echo "weaviate-init: Using embedding model from LITELLM_EMBEDDING_MODEL: $model"

# Create configuration file for Weaviate.
# The embedding model identifier is LiteLLM-prefixed so downstream code can
# pass it straight into LiteLLM's /v1/embeddings request body.
echo "weaviate-init: Creating Weaviate configuration..."
cat > /shared/weaviate-config.env << EOF
# Generated by weaviate-init on $(date)
# Source: LITELLM_EMBEDDING_MODEL env var (set in .env, injected via compose)
LITELLM_EMBEDDING_MODEL=$(quote_shell_env_value "$model")
EOF

echo "weaviate-init: Configuration created:"
cat /shared/weaviate-config.env

echo "weaviate-init: Weaviate configuration process completed successfully."
