-- 02-schemas.sql

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS storage;

-- CREATE SCHEMA IF NOT EXISTS openwebui;
-- GRANT ALL PRIVILEGES ON SCHEMA openwebui TO supabase_admin;

CREATE SCHEMA IF NOT EXISTS n8n;
GRANT ALL PRIVILEGES ON SCHEMA n8n TO supabase_admin;
