-- 11-litellm.sql
-- OWNER: litellm — public.llms catalog, its idempotent migrations, and its
-- updated_at trigger. Only this service's objects belong here.
-- Assembled verbatim from the former 05-public-tables.sql (llms CREATE),
-- 05a-public-tables-migrations.sql (constraint/column/type migrations), and
-- 07-functions.sql (the update_llms_updated_at trigger). The shared
-- update_updated_at_column() function stays in 07-functions.sql, which sorts
-- before this file (07 < 11).

CREATE TABLE IF NOT EXISTS public.llms (
  id bigint generated by default as identity not null,
  active boolean not null default false,
  vision integer not null default 0,
  content integer not null default 0,
  structured_content integer not null default 0,
  embeddings integer not null default 0,
  provider character varying not null,
  name character varying not null,
  description text,
  size_gb numeric,
  context_window integer,
  api_key text,
  api_endpoint text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint llms_pkey primary key (id),
  constraint llms_id_key unique (id),
  constraint llms_name_key unique (name)
);

-- Idempotent migrations (formerly 05a-public-tables-migrations.sql).
-- Safe to re-run; no-ops on fresh installs.
ALTER TABLE public.llms DROP CONSTRAINT IF EXISTS llms_name_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'llms_provider_name_key'
      AND conrelid = 'public.llms'::regclass
  ) THEN
    ALTER TABLE public.llms
      ADD CONSTRAINT llms_provider_name_key UNIQUE (provider, name);
  END IF;
END $$;

ALTER TABLE public.llms
    ADD COLUMN IF NOT EXISTS description text,
    ADD COLUMN IF NOT EXISTS size_gb numeric,
    ADD COLUMN IF NOT EXISTS context_window integer,
    ADD COLUMN IF NOT EXISTS api_key text,
    ADD COLUMN IF NOT EXISTS api_endpoint text;

DO $$
DECLARE
    col text;
BEGIN
    FOREACH col IN ARRAY ARRAY['vision', 'content', 'structured_content', 'embeddings']
    LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public'
               AND table_name = 'llms'
               AND column_name = col
               AND data_type = 'boolean'
        ) THEN
            EXECUTE format('ALTER TABLE public.llms ALTER COLUMN %I DROP DEFAULT', col);
            EXECUTE format('ALTER TABLE public.llms ALTER COLUMN %I TYPE integer USING (CASE WHEN %I THEN 1 ELSE 0 END)', col, col);
            EXECUTE format('ALTER TABLE public.llms ALTER COLUMN %I SET DEFAULT 0', col);
            EXECUTE format('ALTER TABLE public.llms ALTER COLUMN %I SET NOT NULL', col);
            RAISE NOTICE 'public.llms.% converted boolean → integer (legacy volume)', col;
        END IF;
    END LOOP;
END $$;

-- updated_at trigger (formerly in 07-functions.sql). The trigger function
-- update_updated_at_column() is defined in 07-functions.sql (sorts first).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_llms_updated_at'
    ) THEN
        CREATE TRIGGER update_llms_updated_at
            BEFORE UPDATE ON public.llms
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;
