"""Regenerates the <!-- TOPOLOGY:BEGIN --> ... <!-- TOPOLOGY:END --> block in README.md.

Run: cd bootstrapper && uv run python -m tools.generate_readme_topology
"""

from __future__ import annotations

from pathlib import Path

from services.topology import CATEGORY_LABELS, CATEGORY_ORDER, get_topology


def generate_block(services_root: Path) -> str:
    topology = get_topology(services_root)
    lines: list[str] = [
        "<!-- TOPOLOGY:BEGIN -->",
        "_Auto-generated by `bootstrapper/tools/generate_readme_topology.py`._",
        "",
        "_Engine-only manifests (speaches, chatterbox) are not listed — they're "
        "selected as source variants of their parent (STT Provider / TTS Provider) "
        "rather than as standalone services._",
        "",
        "| Category | Service | Default port | Alias |",
        "|---|---|---:|---|",
    ]
    for cat in CATEGORY_ORDER:
        for r in topology.rows:
            if r.category != cat:
                continue
            port = topology.port_defaults.get(r.port_var or "", "—")
            alias = r.alias or "—"
            lines.append(f"| {CATEGORY_LABELS[cat]} | {r.display_name} | {port} | {alias} |")
    lines.append("<!-- TOPOLOGY:END -->")
    return "\n".join(lines) + "\n"


def update_readme(readme_path: Path, services_root: Path) -> None:
    block = generate_block(services_root)
    text = readme_path.read_text()
    start = text.find("<!-- TOPOLOGY:BEGIN -->")
    end = text.find("<!-- TOPOLOGY:END -->")
    if start == -1 or end == -1:
        raise RuntimeError("README.md is missing the TOPOLOGY markers")
    end += len("<!-- TOPOLOGY:END -->")
    new_text = text[:start] + block.rstrip() + text[end:]
    readme_path.write_text(new_text)


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent.parent
    update_readme(project_root / "README.md", project_root / "services")
    print("Updated README.md TOPOLOGY block")
