#!/usr/bin/env python3
"""Validate the checked-in Kong fallback config for direct Compose use.

`./start.sh` may regenerate `volumes/api/kong-dynamic.yml` for SOURCE-specific
routing. The checked-in file still acts as the fallback mounted by plain
`docker compose`, so it must represent the default `.env.example` stack and not
silently drift from documented routes.
"""
from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - developer environment guard
    print("FAIL import: PyYAML is required to parse Kong config", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parents[2]
KONG_CONFIG = ROOT / "volumes/api/kong-dynamic.yml"

EXPECTED_HOST_ROUTES = {
    "comfyui.localhost": "http://comfyui:18188/",
    "n8n.localhost": "http://n8n:5678/",
    "search.localhost": "http://searxng:8080/",
    "jupyter.localhost": "http://jupyterhub:8888/",
    "api.localhost": "http://backend:8000/",
    "chat.localhost": "http://open-web-ui:8080/",
    # openclaw is opt-in: .env.example defaults OPENCLAW_SOURCE=disabled, so
    # the regenerated fallback omits its route. Add an opt-in check separately
    # if the default ever flips to OPENCLAW_SOURCE=container.
}

FORBIDDEN_URLS = {
    "http://host.docker.internal:8000/": "default ComfyUI fallback must target the container service; localhost routing is generated by ./start.sh for COMFYUI_SOURCE=localhost",
}


def load_config() -> dict:
    with KONG_CONFIG.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def host_url_map(config: dict) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for service in config.get("services") or []:
        url = service.get("url")
        for route in service.get("routes") or []:
            for host in route.get("hosts") or []:
                mapping[host] = url
    return mapping


def main() -> int:
    config = load_config()
    hosts = host_url_map(config)
    failed = False

    route_issues = []
    for host, expected_url in EXPECTED_HOST_ROUTES.items():
        actual_url = hosts.get(host)
        if actual_url != expected_url:
            route_issues.append(f"{host}: expected {expected_url}, got {actual_url or 'MISSING'}")

    forbidden_hits = []
    for service in config.get("services") or []:
        url = service.get("url")
        if url in FORBIDDEN_URLS:
            forbidden_hits.append(f"{service.get('name', '<unnamed>')}: {url} ({FORBIDDEN_URLS[url]})")

    if route_issues:
        failed = True
        print("FAIL default_host_routes")
        for issue in route_issues:
            print(f"  {issue}")
    else:
        print("PASS default_host_routes")

    if forbidden_hits:
        failed = True
        print("FAIL forbidden_fallback_urls")
        for hit in forbidden_hits:
            print(f"  {hit}")
    else:
        print("PASS forbidden_fallback_urls")

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
