"""
LiteLLM proxy configuration STUB writer.

The real ``model_list`` is rendered by ``services/litellm/init/scripts/init.py``
from ``public.llms WHERE active = true`` on every ``docker compose up``
— this file produces only a minimal stub on the host so the bind mount
``./volumes/litellm/config.yaml:/app/config.yaml:ro`` has a file to
attach to before the init container has run.

What this writer emits:
  • ``model_list: []`` — to be overwritten by litellm-init.
  • The static settings block (cache, router, general_settings) —
    matches what litellm-init writes, so even if the bootstrapper-
    written stub is somehow loaded by LiteLLM directly (e.g. init
    container crashed), the settings are sane.

What it no longer does:
  • Hardcode model names. Those live in
    ``bootstrapper/utils/llm_catalog.py`` as the single source of
    truth for cloud + Ollama catalogs.

Idempotency rules (see ``write_config``):
  • Existing file managed by litellm-init (sentinel header + non-empty
    model_list) → ALWAYS preserved, even with ``force=True``. The
    previous run's real config survives a re-run that hasn't yet
    completed a docker compose up.
  • Missing file → always written (nothing exists to preserve; the
    ``force`` flag is irrelevant on this path).
  • Stub / corrupt file + ``force=False`` → preserved.
  • Stub / corrupt file + ``force=True`` → overwritten with a fresh
    stub. ``start.py`` calls with force=True at every launch.
"""

from pathlib import Path
from typing import Any, Dict

import yaml

from utils.litellm_settings import base_settings


class LiteLLMConfigGenerator:
    """Writes a stub ``volumes/litellm/config.yaml`` (settings only)."""

    def __init__(self, config_parser):
        self.config_parser = config_parser

    def generate_config(self) -> Dict[str, Any]:
        return {"model_list": [], **base_settings()}

    # Sentinel header written by ``services/litellm/init/scripts/init.py``. When
    # we see this on an existing file, the file is the "real" config
    # rendered from public.llms — leave it alone so re-running
    # ``./start.sh`` and quitting before docker compose up doesn't
    # blow away the user's previous active model_list.
    _LITELLM_INIT_SENTINEL = "# Generated by litellm-init/init.py from public.llms."

    def write_config(self, output_path: Path, force: bool = False) -> bool:
        """Write a stub config.yaml — but only when the existing file
        is missing, our own stub, or unparseable. If the file is the
        real model_list rendered by ``litellm-init``, leave it alone:
        ``litellm-init`` will regenerate it on the next docker compose up.

        Returns True on write, False when the existing file is preserved.
        """
        if output_path.exists():
            if output_path.is_dir():
                # Docker bind-mount creates an empty directory at the source
                # path when the file is missing at `docker compose up` time.
                # Clean that up so we can write a real file in its place.
                try:
                    output_path.rmdir()
                except OSError as e:
                    raise RuntimeError(
                        f"{output_path} exists as a non-empty directory; "
                        "remove it manually before retrying."
                    ) from e
            else:
                # File exists. Decide whether to preserve or overwrite.
                # If it's the real config (sentinel header present) AND
                # has a non-empty model_list, preserve it.
                preserve = self._is_litellm_init_managed(output_path)
                if preserve:
                    return False
                # Stub or corrupt. Without force, also preserve (legacy
                # behaviour); with force, overwrite below.
                if not force:
                    return False

        output_path.parent.mkdir(parents=True, exist_ok=True)
        config = self.generate_config()
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write("# STUB — generated by bootstrapper/utils/litellm_config_generator.py.\n")
            fh.write("# The real model_list is rendered by litellm-init from public.llms\n")
            fh.write("# on every `docker compose up`. Don't edit this stub by hand —\n")
            fh.write("# change models via the wizard or `psql ... UPDATE public.llms ...`.\n\n")
            yaml.safe_dump(config, fh, sort_keys=False, default_flow_style=False)
        return True

    @classmethod
    def _is_litellm_init_managed(cls, path: Path) -> bool:
        """True when the file's first non-empty line is the litellm-init
        sentinel AND its parsed ``model_list`` is non-empty. This signals
        ``litellm-init`` rendered it on the last successful run.
        """
        try:
            with open(path, "r", encoding="utf-8") as fh:
                head = fh.read(2048)  # cheap header peek
        except OSError:
            return False
        if cls._LITELLM_INIT_SENTINEL not in head:
            return False
        # Verify the YAML parses and has a non-empty model_list. A
        # corrupt or empty real config gets overwritten by the stub.
        try:
            with open(path, "r", encoding="utf-8") as fh:
                doc = yaml.safe_load(fh)
        except (yaml.YAMLError, OSError):
            return False
        if not isinstance(doc, dict):
            return False
        model_list = doc.get("model_list")
        return isinstance(model_list, list) and len(model_list) > 0
