#!/bin/bash
# GenAI Vanilla Stack - JupyterHub Startup Script
# Initializes environment and starts Jupyter Lab

set -e

echo "🚀 Starting JupyterHub for GenAI Vanilla Stack..."

# Display environment information
echo "📋 Environment Configuration:"
echo "  • Ollama: ${OLLAMA_BASE_URL:-not configured}"
echo "  • Weaviate: ${WEAVIATE_URL:-not configured}"
echo "  • Neo4j: ${NEO4J_URI:-not configured}"
echo "  • ComfyUI: ${COMFYUI_BASE_URL:-not configured}"
echo "  • Database: ${DATABASE_URL:+configured}"
echo "  • Redis: ${REDIS_URL:+configured}"
echo "  • Supabase: ${SUPABASE_URL:-not configured}"

# Create .env file in work directory with all environment variables
cat > /home/jovyan/work/.env << EOF
# GenAI Vanilla Stack Environment Variables
# Auto-generated by startup script

# AI Services
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
WEAVIATE_URL=${WEAVIATE_URL:-http://weaviate:8080}
NEO4J_URI=${NEO4J_URI:-bolt://neo4j-graph-db:7687}
NEO4J_USER=${NEO4J_USER:-neo4j}
NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
COMFYUI_BASE_URL=${COMFYUI_BASE_URL:-http://comfyui:18188}

# Database
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=${REDIS_URL:-}

# Supabase
SUPABASE_URL=${SUPABASE_URL:-http://kong-api-gateway:8000}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}

# Additional Services
N8N_BASE_URL=${N8N_BASE_URL:-http://n8n:5678}
SEARXNG_URL=${SEARXNG_URL:-http://searxng:8080}
BACKEND_API_URL=${BACKEND_API_URL:-http://backend:8000}
EOF

echo "✅ Environment file created at /home/jovyan/work/.env"

# Copy sample notebooks to work directory for easy access
if [ -d /home/jovyan/notebooks ] && [ ! -d /home/jovyan/work/examples ]; then
    echo "📓 Copying sample notebooks to work/examples/..."
    mkdir -p /home/jovyan/work/examples
    cp -r /home/jovyan/notebooks/* /home/jovyan/work/examples/
    echo "✅ Sample notebooks copied to /home/jovyan/work/examples/"
fi

# Create a welcome README in the work directory
if [ ! -f /home/jovyan/work/README.md ]; then
    cat > /home/jovyan/work/README.md << 'EOF'
# Welcome to JupyterHub - GenAI Vanilla Stack

This Jupyter environment is pre-configured to work with all services in the GenAI Vanilla Stack.

## 📚 Sample Notebooks

Check the `examples/` directory for sample notebooks demonstrating:
- `00_environment_check.ipynb` - Verify all service connections
- `01_ollama_basics.ipynb` - LLM integration with Ollama
- `02_langchain_rag.ipynb` - RAG pipeline with Weaviate
- `03_neo4j_graphs.ipynb` - Knowledge graphs with Neo4j
- `04_supabase_data.ipynb` - Database and storage operations
- `05_comfyui_images.ipynb` - Image generation with ComfyUI
- `06_n8n_workflows.ipynb` - Workflow automation with n8n

## 🔧 Available Services

All service URLs are available as environment variables:
- `OLLAMA_BASE_URL` - LLM inference
- `WEAVIATE_URL` - Vector database
- `NEO4J_URI` - Graph database
- `DATABASE_URL` - PostgreSQL via Supabase
- `REDIS_URL` - Cache and queue
- `SUPABASE_URL` - Supabase API gateway
- `COMFYUI_BASE_URL` - Image generation
- `N8N_BASE_URL` - Workflow automation
- `SEARXNG_URL` - Privacy-focused search
- `BACKEND_API_URL` - Backend API

## 💡 Quick Start

```python
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Access services
ollama_url = os.getenv("OLLAMA_BASE_URL")
print(f"Ollama endpoint: {ollama_url}")
```

## 📖 Documentation

For more information, visit: http://localhost:63009 (Supabase Studio)
EOF
    echo "✅ Welcome README created"
fi

# Display startup message
echo ""
echo "🎉 JupyterHub is ready!"
echo "📂 Your work directory: /home/jovyan/work"
echo "📓 Sample notebooks: /home/jovyan/work/examples"
echo ""

# Execute the original entrypoint with arguments
exec "$@"
